### ISSUE TITLE
odata v4 query

### ISSUE THREAD

**Issue by ahmed-sherien** [devnixs/ODataAngularResources#65]
I've been playing with the library all day but things weren't smooth with me ...
I keep getting an error that 'odata' or 'query' was expecting an array while they got an object instead ...
here's my app.js

``` javascript
(function(){
    var app = angular.module("access-control", ["ngRoute", "ODataResources"]);
    app.config(function($routeProvider) {
        $routeProvider
            .when("/main", {
                templateUrl: "views/main.html",
                controller: "MainController"
            })
            .when("/error", {
                templateUrl: "views/error.html"
            })
            .when("/admin", {
                templateUrl: "views/admin.html",
                controller: "AdminController"
            })
            .when("/admin/forms", {
                templateUrl: "views/admin/forms.html",
                controller: "FormsController"
            })
            .otherwise({ redirectTo: "/error" });
    });
}())
```

and here is my controller

``` javascript
(function () {
    var formsController = function ($scope, $log, $odataresource) {
        var onError = function (reason) {
            $log.error("fail ...");
        }
        var onFormsComplete = function (response) {
            $log.log("completed ...");
        }
        var forms = $odataresource("http://localhost:4744/odata/Forms");
        var myforms = forms.odata().query(onFormsComplete,onError);
        $scope.forms = myforms;
    };
    var app = angular.module("access-control");
    app.controller("FormsController", ["$scope", "$log", "$odataresource", formsController]);
}())
```

and here is my response

``` json
{
  "odata.metadata":"http://localhost:4744/odata/$metadata#Forms",
  "value":[
    {
      "Title":"Form 1",
      "Subtitle":null,
      "Id":"5ac87c3d-07a6-4f90-8849-2e04ceecc61b",
      "CreatedOn":"2016-05-05T00:00:00",
      "LastModifiedOn":"2016-05-05T00:00:00"
    }
  ]
}
```

it never gets in `onFormsComplete` nor `onError` ...

I'm still new to the front-end and angular thing so please bear with me ...

**Comment by ahmed-sherien** [comment]
Now I used `ngResource` and it worked fine but I needed to use `get()` instead of `query()` and also I had to do `$scope.forms = response.value` in `onFormsComplete` function ...

**Comment by devnixs** [comment]
I think you're using an OData V4 endpoint, be sure to update your configuration accordingly : 
https://github.com/devnixs/ODataAngularResources#odata-v4-support
If that works, you won't have to use get() instead of query()

**Comment by ahmed-sherien** [comment]
I updated the controller to do this

``` javascript
var forms = $odataresource("http://localhost:4744/odata/Forms", {}, {}, {
            odatakey: "id",
            isodatav4: true
        });
var myforms = forms.odata().query();
$scope.forms = myforms;
```

but it still gives the same error ...

**Comment by devnixs** [comment]
Your response contains "odata.metadata" instead of "@odata.context"
That's why the library doesn't recognize it.
You should either use an interceptor to update the response, or submit a pull request that fixes that

**Comment by devnixs** [comment]
Nevermind, I just published a fix.
Let me know if that works

**Comment by ahmed-sherien** [comment]
I updated to version `1.0.19`
and here is my dependencies

``` json
"dependencies": {
    "angular-odata-resources": "^1.0.19",
    "angular-resource": "1.5.5",
    "bootstrap": "^3.3.6",
    "angular-route": "1.5.5",
    "angular": "1.5.5"
  }
```

the problem is still there ...

**Comment by kyse** [comment]
`if (data && (angular.isString(data['@odata.context']) || angular.isString(data['odata.context']) ) && data.value && angular.isArray(data.value)) {`

He removed the @, but forgot to change context to metadata in the second check, so yes, it would still fail for you.

**Comment by devnixs** [comment]
My bad. It's fixed

**Comment by ahmed-sherien** [comment]
the update is made in `src` but not in `build` ...

**Comment by devnixs** [comment]
Here you go:
https://github.com/devnixs/ODataAngularResources/releases/tag/1.0.21

**Comment by ahmed-sherien** [comment]
Great ... at last ... it is working perfectly now ... thanks :smile:
